# apiVersion: v1
# kind: Service
# metadata:
#   name: echoserver
#   namespace: echoserver
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip" # Specifies ALB type
#     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
# spec:
#   type: LoadBalancer
#   selector:
#     app: echoserver
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   loadBalancerSourceRanges:
#     - "10.0.0.0/8"  # Replace with your allowed CIDR block
#     - "176.16.0.0/12" # Additional allowed CIDR block


apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
    - host: echoserver.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80