#:schema node_modules/wrangler/config-schema.json
name = "astro-poc"
compatibility_date = "2024-11-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
testVar = "prod"

[[kv_namespaces]]
binding = "astro-poc-sample"
id = "6b4760b8e3c74f5a8c57f4f74fc9535f"

[[d1_databases]]
binding = "test-poc-db"
database_name = "astro-poc"
database_id = "32da2e81-48b7-4099-8fdd-4c426311b3ed"
# preview_database_id = "test-poc-db"
migrations_dir = "drizzle/test-poc"